#!/bin/sh
# mkauthorities.sh -- kernel/net/authorities.h from tools/pki/authorities.txt: the trusted authorities' public keys.
# - each line of the list: <pem file in tools/pki/authorities> | <name the log uses>
# - only the SubjectPublicKeyInfo of each certificate goes into the kernel; the name and expiry are comments
cd "$(dirname "$0")/.."
OUT=kernel/net/authorities.h
i=0
table=""
{
    echo "/* authorities.h -- generated by tools/mkauthorities.sh from tools/pki/authorities.txt; do not edit. */"
    while IFS='|' read -r file name; do
        file=$(echo "$file" | sed 's/^ *//; s/ *$//')
        name=$(echo "$name" | sed 's/^ *//; s/ *$//')
        [ -n "$file" ] || continue
        until=$(openssl x509 -in tools/pki/authorities/$file -noout -enddate | sed 's/notAfter=//')
        subject=$(openssl x509 -in tools/pki/authorities/$file -noout -subject | sed 's/subject=//')
        echo "/* $name: $subject; valid until $until */"
        echo "static const u8 AUTH_$i[] = {"
        openssl x509 -in tools/pki/authorities/$file -pubkey -noout | openssl pkey -pubin -outform DER \
            | od -An -v -tx1 | sed 's/ \([0-9a-f][0-9a-f]\)/0x\1,/g; s/^/   /'
        echo "};"
        table="$table    { \"$name\", AUTH_$i, sizeof AUTH_$i },
"
        i=$((i + 1))
    done < tools/pki/authorities.txt
    echo "static const pki_authority AUTHORITIES[] = {"
    printf '%s' "$table"
    echo "};"
} > $OUT
echo "wrote $OUT with $i authorities"
